# -*- coding: utf-8 -*-
"""Exploratory Data Analysis - Secondary Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NdbpNsTlzHtykI9uvDcVLRLYsNV2iy2J
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

secondary_df = pd.read_csv('geopolitical_conflict_risk_dataset.csv')

display(secondary_df.head())
secondary_df.info()

display(secondary_df.describe())

plt.figure(figsize=(10, 6))
sns.histplot(data=secondary_df, x='instability_score', bins=30, kde=True)
plt.show()

secondary_df['month'] = pd.to_datetime(secondary_df['month'])
global_trend = secondary_df.groupby('month')['instability_score'].mean().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(data=global_trend, x='month', y='instability_score', marker='o')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10, 4))
sns.boxplot(data=secondary_df, x='instability_score')
plt.show()

corr_matrix = secondary_df.select_dtypes(include=['float64', 'int64']).corr()

plt.figure(figsize=(18, 14))
sns.heatmap(corr_matrix , cmap='coolwarm', center=0)
plt.show()